import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = localFont({
  src: "./fonts/Montserrat-ExtraBold.woff2",
  variable: "--font-montserratextrabold",
  weight: "800",
});
const zonapro = localFont({
  src: "./fonts/ZonaPro-Black.woff2",
  variable: "--font-zonaproblack",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
